package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/token"
	"strings"
)

// The files M10's class A commit moves the rest of the registry's file to,
// and the header each gets when declmove creates it.
const (
	helpersFile   = "migration_helpers.go"
	helpersHeader = "// Declarations the numbered migrations reach (refactor plan M10; the\n" +
		"// declmove spec came from internal/tools/liftmigrations). The stored-data\n" +
		"// freeze hashes each with every migration that reaches it\n" +
		"// (testdata/freeze/migrations.txt), so none of them ever changes: a new\n" +
		"// migration that needs something else declares something new."
	runnerFile   = "migrate_runner.go"
	runnerHeader = "// The migration runner (refactor plan M10; the declmove spec came from\n" +
		"// internal/tools/liftmigrations): the boot lock, the ledger, Migrate and\n" +
		"// MigrateAndBackfill, the runner that applies the registry in\n" +
		"// migrations.go, and the extension reconcile. The stored-data freeze\n" +
		"// hashes every declaration here (testdata/freeze/every_boot.txt)."
)

// moveSpec is a declmove spec (internal/tools/declmove/move.go).
type moveSpec struct {
	Description string       `json:"description"`
	Package     string       `json:"package"`
	Targets     []moveTarget `json:"targets"`
}

type moveTarget struct {
	File   string   `json:"file"`
	Header string   `json:"header,omitempty"`
	Decls  []string `json:"decls"`
}

// planMove works out the declmove spec of M10's class A commit: every
// declaration of the registry's file but the registry, its element type and
// that type's methods leaves it. What a registry entry reaches, directly or
// through other declarations of the package, goes to migration_helpers.go;
// the rest (the runner, the ledger, the locks, the reconcile) to
// migrate_runner.go. Each keeps its order. It returns nil when nothing is
// left to move.
func planMove(p *pkgSource, pkgPath string) (*moveSpec, error) {
	regDecl, lit, err := p.registry()
	if err != nil {
		return nil, err
	}
	reached := p.reach(map[*declInfo]bool{regDecl: true}, lit)
	elemType := p.decls[p.pkg.Scope().Lookup(registryType)]
	byNode := map[ast.Decl]*declInfo{}
	for _, d := range p.decls {
		byNode[d.node] = d
	}
	var helpers, runner []string
	var errs []string
	for _, node := range regDecl.file.ast.Decls {
		if gd, ok := node.(*ast.GenDecl); ok && gd.Tok == token.IMPORT {
			continue
		}
		d := byNode[node]
		if d == nil {
			errs = append(errs, fmt.Sprintf("%s: a declaration liftmigrations cannot name (a blank _ or an init function); move it by hand first",
				p.where(node.Pos())))
			continue
		}
		if d == regDecl || d == elemType || isMethodOf(node, registryType) {
			continue
		}
		for _, k := range d.keys {
			if k == "_" || k == "init" {
				errs = append(errs, fmt.Sprintf("%s: %s cannot be named in a declmove spec; move it by hand first", p.where(node.Pos()), k))
			}
		}
		if reached[d] {
			helpers = append(helpers, d.keys...)
		} else {
			runner = append(runner, d.keys...)
		}
	}
	if len(errs) > 0 {
		return nil, fmt.Errorf("%s", strings.Join(errs, "\n"))
	}
	if len(helpers)+len(runner) == 0 {
		return nil, nil
	}
	sp := &moveSpec{
		Description: fmt.Sprintf("Refactor plan M10, class A commit: the helpers the numbered migrations reach leave %s for %s, "+
			"and the runner for %s. Generated by go run ./internal/tools/liftmigrations -spec <this file>; "+
			"apply it with go run ./internal/tools/declmove -spec <this file>.", regDecl.file.name, helpersFile, runnerFile),
		Package: pkgPath,
	}
	if len(helpers) > 0 {
		sp.Targets = append(sp.Targets, moveTarget{File: helpersFile, Header: helpersHeader, Decls: helpers})
	}
	if len(runner) > 0 {
		sp.Targets = append(sp.Targets, moveTarget{File: runnerFile, Header: runnerHeader, Decls: runner})
	}
	return sp, nil
}

// isMethodOf reports whether a declaration is a method of the named type.
func isMethodOf(node ast.Decl, typeName string) bool {
	fd, ok := node.(*ast.FuncDecl)
	if !ok || fd.Recv == nil || len(fd.Recv.List) != 1 {
		return false
	}
	return strings.Trim(receiverKey(fd.Recv.List[0].Type), "(*)") == typeName
}

// encode renders the spec as the files under internal/tools/declmove/specs
// are written.
func (sp *moveSpec) encode() ([]byte, error) {
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(sp); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}
