package chatter

import (
	"errors"
	"time"

	"github.com/google/uuid"
)

// ChatterEntry represents a comment or note on an artifact
type ChatterEntry struct {
	ID          string `json:"id"`
	ArtifactID  string `json:"artifact_id"`
	Message     string `json:"message"`
	IsAutoEntry bool   `json:"is_auto_entry"` // true if auto-generated by system, false if user-entered
	EntryType   string `json:"entry_type"`    // "comment", "version-change", "link-change", etc.
	// CreatedBy is the id of the authenticated user who authored the entry, or
	// nil for agent-authored and system-generated entries (which have no user
	// identity). AuthorName is the display name resolved at write time — the
	// user's name/email, or the agent name for run-authored entries — so the
	// feed can attribute an entry without a follow-up user/run lookup. Both are
	// blank on pre-authorship rows; no backfill is attempted.
	CreatedBy  *string   `json:"created_by,omitempty"`
	AuthorName string    `json:"author_name"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`

	// Mentions and Todo are resolved for display and never stored: the
	// note's text is the record of who it names, and the work item is the
	// record of the to-do. Both are composed by the API when a feed is
	// read, so a status shown beside a note is the item's status now
	// rather than a copy taken when the note was written.
	Mentions []MentionRef `json:"mentions,omitempty"`
	Todo     *TodoRef     `json:"todo,omitempty"`
}

// MentionRef is a project member a note addresses by @name.
type MentionRef struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

// TodoRef is the to-do raised from a note, as much of it as the note needs
// to show a link and a status.
type TodoRef struct {
	WorkItemID string `json:"work_item_id"`
	Title      string `json:"title"`
	// Status is the board column the item sits in.
	Status       string  `json:"status"`
	AssigneeID   *string `json:"assignee_id,omitempty"`
	AssigneeName string  `json:"assignee_name,omitempty"`
}

// CreateChatterEntryRequest is the payload for creating a chatter entry
type CreateChatterEntryRequest struct {
	ArtifactID string `json:"artifact_id"`
	Message    string `json:"message"`
}

// NewChatterEntry creates a new chatter entry
func NewChatterEntry(artifactID, message string, isAutoEntry bool, entryType string) *ChatterEntry {
	now := time.Now()
	return &ChatterEntry{
		ID:          uuid.New().String(),
		ArtifactID:  artifactID,
		Message:     message,
		IsAutoEntry: isAutoEntry,
		EntryType:   entryType,
		CreatedAt:   now,
		UpdatedAt:   now,
	}
}

// Service defines chatter domain logic
type Service interface {
	CreateEntry(entry *ChatterEntry) error
	GetEntriesByArtifactID(artifactID string) ([]*ChatterEntry, error)
	// GetEntry returns one note. Used to check that a note a to-do claims
	// to come from exists and belongs to the same project.
	GetEntry(id string) (*ChatterEntry, error)
}

// Repository defines persistence operations for chatter
type Repository interface {
	Save(entry *ChatterEntry) error
	FindByArtifactID(artifactID string) ([]*ChatterEntry, error)
	FindByID(id string) (*ChatterEntry, error)
	Delete(id string) error
}

// DefaultService implements the Service interface
type DefaultService struct {
	repo Repository
}

// NewDefaultService creates a new chatter service
func NewDefaultService(repo Repository) *DefaultService {
	return &DefaultService{repo: repo}
}

// CreateEntry creates a new chatter entry
func (s *DefaultService) CreateEntry(entry *ChatterEntry) error {
	return s.repo.Save(entry)
}

// GetEntriesByArtifactID retrieves all chatter entries for an artifact
func (s *DefaultService) GetEntriesByArtifactID(artifactID string) ([]*ChatterEntry, error) {
	return s.repo.FindByArtifactID(artifactID)
}

// ErrNotFound reports a note that does not exist.
var ErrNotFound = errors.New("chatter entry not found")

// GetEntry returns one note by id.
func (s *DefaultService) GetEntry(id string) (*ChatterEntry, error) {
	return s.repo.FindByID(id)
}
