#!/usr/bin/env python3
"""Build frontend/src/brand/tokens.css from docs/brand/tokens.json.

docs/brand/tokens.json is the brand's source of truth (see
docs/brand/README.md). This script turns it into CSS custom properties: one
property per token, the light values on the scope selector and the dark
values under both the `prefers-color-scheme: dark` media query (unless the
viewer chose light) and an explicit `[data-theme="dark"]`, the same three
states theme.css handles. It also writes the IBM Plex @font-face rules and
one class per type style (.ov-type-<name>).

The scope is `.ov-brand` while the app still runs on theme.css: only the
public site wears the brand. With --legacy-aliases the old theme.css names
(--accent, --text-body, --tint-blue, ...) resolve to the new tokens inside
the scope, so markup not yet rewritten already takes the new palette
(docs/brand/migration.md, step 1).

Stdlib only.

    python3 scripts/brand/build_tokens.py            # write the file
    python3 scripts/brand/build_tokens.py --check    # exit 1 if it is stale
"""

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SOURCE = ROOT / "docs" / "brand" / "tokens.json"
TARGET = ROOT / "frontend" / "src" / "brand" / "tokens.css"
SCOPE = ".ov-brand"
FONT_URL = "/fonts/"

# Old theme.css custom properties and the brand token each now means. Names
# the brand reuses (--text, --surface, --border, --success, ...) need no
# alias: the brand token of the same name replaces them inside the scope.
LEGACY_ALIASES = [
    ("bg-app", "bg"),
    ("surface-alt", "surface-hover"),
    ("surface-inset", "surface-sunken"),
    ("border-soft", "border"),
    ("neutral-soft", "neutral-chip"),
    ("neutral-mid", "border-control"),
    ("neutral", "text-muted"),
    ("text-body", "text-secondary"),
    ("accent", "primary"),
    ("accent-strong", "primary-hover"),
    ("accent-alt", "primary"),
    ("accent-text", "link"),
    ("accent-fg", "text-on-primary"),
    ("success-bright", "success"),
    ("success-strong", "success"),
    ("success-text", "success"),
    ("danger-strong", "danger"),
    ("danger-text", "danger"),
    ("warning-bright", "warning"),
    ("warning-strong", "warning"),
    ("warning-text", "warning"),
    ("purple", "agent"),
    ("purple-soft", "agent"),
    ("purple-strong", "agent"),
    ("tint-blue", "info-bg"),
    ("tint-blue-border", "border"),
    ("tint-green", "success-bg"),
    ("tint-green-border", "success-border"),
    ("tint-red", "danger-bg"),
    ("tint-red-border", "danger-border"),
    ("tint-yellow", "warning-bg"),
    ("tint-yellow-border", "warning-border"),
    ("tint-purple", "agent-bg"),
    ("tint-purple-border", "agent-border"),
    ("sidebar-bg", "surface"),
    ("sidebar-border", "border"),
    ("sidebar-menu-bg", "surface-hover"),
    ("sidebar-text", "text"),
    ("sidebar-text-dim", "text-secondary"),
    ("sidebar-text-faint", "text-muted"),
    ("code-block-bg", "surface-sunken"),
    ("code-block-text", "text"),
]


def value_for(token, theme, first):
    v = token["value"]
    if isinstance(v, str):
        return v if theme == first else None
    if theme in v:
        return v[theme]
    return None


def css_value(v):
    # "{other}" aliases a colour token.
    if v.startswith("{") and v.endswith("}"):
        return "var(--%s)" % v[1:-1]
    return v


def dark_selectors(scope):
    if scope == ":root":
        return ':root:not([data-theme="light"])', ':root[data-theme="dark"]'
    return ':root:not([data-theme="light"]) %s' % scope, ':root[data-theme="dark"] %s' % scope


def build(tokens, scope, legacy):
    themes = [t["id"] for t in tokens["color"]["themes"]]
    first = themes[0]
    themed = tokens["color"]["tokens"] + tokens.get("shadow", {}).get("tokens", [])
    plain_families = ["spacing", "radius", "size"]

    out = [
        "/*",
        " * GENERATED by scripts/brand/build_tokens.py from docs/brand/tokens.json.",
        " * Do not edit: change tokens.json and run the script.",
        " */",
        "",
    ]

    for font in tokens["type"].get("fonts", []):
        name = pathlib.PurePosixPath(font["file"]).name
        out += [
            "@font-face {",
            "  font-family: \"%s\";" % font["family"],
            "  src: url(\"%s%s\") format(\"woff2\");" % (FONT_URL, name),
            "  font-weight: %s;" % font["weight"],
            "  font-style: %s;" % font.get("style", "normal"),
            "  font-display: swap;",
            "}",
            "",
        ]

    out.append("%s {" % scope)
    for key, stack in tokens["type"]["families"].items():
        out.append("  --font-%s: %s;" % (key, stack))
    for t in themed:
        v = value_for(t, first, first)
        if v is not None:
            out.append("  --%s: %s;" % (t["name"], css_value(v)))
    for fam in plain_families:
        for t in tokens.get(fam, {}).get("tokens", []):
            out.append("  --%s: %s;" % (t["name"], t["value"]))
    if legacy:
        out.append("  /* theme.css names, until every site component uses the brand names */")
        for old, new in LEGACY_ALIASES:
            out.append("  --%s: var(--%s);" % (old, new))
    out += ["}", ""]

    for theme in themes[1:]:
        lines = []
        for t in themed:
            v = value_for(t, theme, first)
            if v is not None:
                lines.append("  --%s: %s;" % (t["name"], css_value(v)))
        if theme == "dark":
            media, explicit = dark_selectors(scope)
            out.append("@media (prefers-color-scheme: dark) {")
            out.append("  %s {" % media)
            out += ["  " + l for l in lines]
            out.append("    color-scheme: dark;")
            out += ["  }", "}", "", "%s {" % explicit]
            out += lines
            out += ["  color-scheme: dark;", "}", ""]
        else:
            out.append('%s[data-theme="%s"], [data-theme="%s"] %s {' % (scope, theme, theme, scope))
            out += lines
            out += ["}", ""]

    for group in tokens["type"]["groups"]:
        for s in group["styles"]:
            fam = s.get("family", group.get("family", "sans"))
            rule = [".ov-type-%s {" % s["name"], "  font-family: var(--font-%s);" % fam]
            rule.append("  font-size: %s;" % s["fontSize"])
            if "lineHeight" in s:
                rule.append("  line-height: %s;" % s["lineHeight"])
            if "fontWeight" in s:
                rule.append("  font-weight: %s;" % s["fontWeight"])
            if "letterSpacing" in s:
                rule.append("  letter-spacing: %s;" % s["letterSpacing"])
            rule += ["}", ""]
            out += rule

    return "\n".join(out).rstrip() + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the generated file is out of date")
    ap.add_argument("--scope", default=SCOPE, help="selector the tokens are defined on (default %(default)s)")
    ap.add_argument("--no-legacy-aliases", action="store_true", help="omit the theme.css name aliases")
    args = ap.parse_args()

    tokens = json.loads(SOURCE.read_text(encoding="utf-8"))
    css = build(tokens, args.scope, not args.no_legacy_aliases)
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != css:
            print("%s is out of date: run scripts/brand/build_tokens.py" % TARGET.relative_to(ROOT), file=sys.stderr)
            return 1
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(css, encoding="utf-8")
    print("wrote %s" % TARGET.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
