package mcp

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"
)

// jsonrpcGoldenPath pins the bytes openv-mcp writes to stdout (invariant
// I11): agent CLIs parse these lines, so the envelope, the key order, the
// error codes and texts and the fixed protocol and server versions are all
// part of the compatibility promise (REQ-143).
var jsonrpcGoldenPath = filepath.Join("testdata", "jsonrpc.txt")

// jsonrpcGoldenAllowlist narrows the served table the way an agent's
// allowlist does (REQ-91), which keeps the tools/list line short: the full
// table is pinned by testdata/tools.json.
const jsonrpcGoldenAllowlist = "mcp__openv__get_vv_gaps,list_projects"

const jsonrpcGoldenToken = "run-token-golden"

const jsonrpcGoldenHeader = `# openv-mcp JSON-RPC 2.0 over stdio (MCP 2024-11-05), served the way
# cmd/openv-mcp serves it: ServeStdio(NewClient(<stub API>, "` + jsonrpcGoldenToken + `"), Tools()).
# ">" is a line written to stdin; "<" is the exact line written back to
# stdout (one JSON object per newline-terminated line); "=" is a REST request
# the stub OpenV API received while that line was served.
# Generated by TestMCPJSONRPCGolden in internal/mcp.
`

// rpcGoldenStep is one line sent to the server. answered says whether the
// server writes a line back for it.
type rpcGoldenStep struct {
	note     string
	line     string
	answered bool
}

func rpcGoldenSteps() []rpcGoldenStep {
	return []rpcGoldenStep{
		{"initialize: the protocol version and the server name and version are fixed",
			`{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"golden","version":"0"}}}`, true},
		{"the initialized notification gets no response",
			`{"jsonrpc":"2.0","method":"notifications/initialized"}`, false},
		{"ping; a string id is echoed back as the same raw JSON",
			`{"jsonrpc":"2.0","id":"ping-1","method":"ping"}`, true},
		{"tools/list: the tools " + EnvToolAllowlist + " admits, in table order",
			`{"jsonrpc":"2.0","id":2,"method":"tools/list"}`, true},
		{"a successful tools/call: the API body, trimmed, is the one text block",
			`{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"list_projects","arguments":{}}}`, true},
		{"a tools/call the API refuses is a result with isError, not a JSON-RPC error",
			`{"jsonrpc":"2.0","id":4,"method":"tools/call","params":{"name":"get_vv_gaps","arguments":{"project_id":"` + goldenProjectID + `"}}}`, true},
		{"a tool the allowlist leaves out is an unknown tool (-32602)",
			`{"jsonrpc":"2.0","id":5,"method":"tools/call","params":{"name":"create_artifact","arguments":{"project_id":"` + goldenProjectID + `"}}}`, true},
		{"tools/call params that are not an object (-32602)",
			`{"jsonrpc":"2.0","id":6,"method":"tools/call","params":[1,2]}`, true},
		{"an unknown method with an id (-32601)",
			`{"jsonrpc":"2.0","id":7,"method":"resources/list"}`, true},
		{"an unknown notification gets no response",
			`{"jsonrpc":"2.0","method":"notifications/cancelled","params":{"requestId":3}}`, false},
		{"a line that is not JSON (-32700, id null)",
			`this is not json`, true},
		{"the loop keeps serving after a parse error",
			`{"jsonrpc":"2.0","id":8,"method":"ping"}`, true},
	}
}

// TestMCPJSONRPCGolden pins the openv-mcp JSON-RPC encodings: initialize,
// tools/list, a successful tools/call, a tool error, and the JSON-RPC error
// responses, byte for byte, with a stub API behind the tools.
func TestMCPJSONRPCGolden(t *testing.T) {
	t.Setenv(EnvToolAllowlist, jsonrpcGoldenAllowlist)
	api, requests := rpcStubAPI(t)
	proc := startStdioProcess(t, NewClient(api.URL, jsonrpcGoldenToken), Tools())

	var b strings.Builder
	b.WriteString(jsonrpcGoldenHeader)
	fmt.Fprintf(&b, "# %s=%s\n", EnvToolAllowlist, jsonrpcGoldenAllowlist)
	for _, step := range rpcGoldenSteps() {
		fmt.Fprintf(&b, "\n# %s\n> %s\n", step.note, step.line)
		before := len(requests())
		proc.write(step.line + "\n")
		if !step.answered {
			b.WriteString("< (no response)\n")
			continue
		}
		line := proc.readLine()
		for _, r := range requests()[before:] {
			fmt.Fprintf(&b, "= %s\n", r)
		}
		b.WriteString("< " + line)
	}
	fmt.Fprintf(&b, "\n# stdin closed\nServeStdio returned %v\n", proc.stop())
	for _, extra := range proc.drain() {
		b.WriteString("< " + extra)
	}
	checkGolden(t, jsonrpcGoldenPath, []byte(b.String()), "TestMCPJSONRPCGolden")
}

// rpcStubAPI is the OpenV API behind the transcript: list_projects succeeds,
// get_vv_gaps is refused with the API's error envelope, and anything else is
// a 404. It returns every request it has seen, as METHOD URI and credential.
func rpcStubAPI(t *testing.T) (*httptest.Server, func() []string) {
	t.Helper()
	var mu sync.Mutex
	var seen []string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		seen = append(seen, fmt.Sprintf("%s %s (Authorization: %s)", r.Method, r.URL.RequestURI(), r.Header.Get("Authorization")))
		mu.Unlock()
		w.Header().Set("Content-Type", "application/json")
		switch {
		case r.Method == http.MethodGet && r.URL.Path == "/api/v1/projects":
			_, _ = io.WriteString(w, `[{"id":"`+goldenProjectID+`","name":"Pump controller"}]`+"\n")
		case r.Method == http.MethodGet && r.URL.Path == "/api/v1/projects/"+goldenProjectID+"/vv/gaps":
			w.WriteHeader(http.StatusForbidden)
			_, _ = io.WriteString(w, `{"error":"forbidden","code":"forbidden"}`+"\n")
		default:
			w.WriteHeader(http.StatusNotFound)
			_, _ = io.WriteString(w, `{"error":"not found"}`+"\n")
		}
	}))
	t.Cleanup(srv.Close)
	return srv, func() []string {
		mu.Lock()
		defer mu.Unlock()
		return append([]string(nil), seen...)
	}
}

// stdioProcess runs ServeStdio, the entry point cmd/openv-mcp calls, with the
// process's stdin and stdout swapped for pipes, so the test reads exactly the
// bytes the binary writes. A test using it must not run in parallel.
type stdioProcess struct {
	t      *testing.T
	stdin  *os.File
	stdout *os.File
	lines  chan string
	done   chan error

	once   sync.Once
	result error
}

func startStdioProcess(t *testing.T, client *Client, tools []Tool) *stdioProcess {
	t.Helper()
	inR, inW, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	outR, outW, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	origIn, origOut := os.Stdin, os.Stdout
	os.Stdin, os.Stdout = inR, outW
	p := &stdioProcess{t: t, stdin: inW, stdout: outW, lines: make(chan string, 64), done: make(chan error, 1)}
	go func() { p.done <- ServeStdio(client, tools) }()
	go func() {
		defer close(p.lines)
		r := bufio.NewReader(outR)
		for {
			line, err := r.ReadString('\n')
			if line != "" {
				p.lines <- line
			}
			if err != nil {
				return
			}
		}
	}()
	t.Cleanup(func() {
		_ = p.stop()
		os.Stdin, os.Stdout = origIn, origOut
		_ = outW.Close()
		_ = inR.Close()
		_ = outR.Close()
	})
	return p
}

func (p *stdioProcess) write(s string) {
	p.t.Helper()
	if _, err := io.WriteString(p.stdin, s); err != nil {
		p.t.Fatalf("write to the server's stdin: %v", err)
	}
}

// readLine returns the next line the server wrote, newline included.
func (p *stdioProcess) readLine() string {
	p.t.Helper()
	select {
	case line, ok := <-p.lines:
		if !ok {
			p.t.Fatal("the server's stdout closed while a response was expected")
		}
		return line
	case <-time.After(10 * time.Second):
		p.t.Fatal("timed out waiting for a response line")
		return ""
	}
}

// stop closes the server's stdin and returns what ServeStdio returned.
func (p *stdioProcess) stop() error {
	p.once.Do(func() {
		_ = p.stdin.Close()
		select {
		case p.result = <-p.done:
		case <-time.After(10 * time.Second):
			p.result = errors.New("ServeStdio did not return after stdin EOF")
		}
	})
	return p.result
}

// drain closes the server's stdout and returns the lines no step read.
func (p *stdioProcess) drain() []string {
	_ = p.stdout.Close()
	var rest []string
	for line := range p.lines {
		rest = append(rest, line)
	}
	return rest
}

// TestServeStdioReturnsAtEOFWithoutWaitingForInFlightCalls pins
// agent-exec-15 as it stands: on stdin EOF the loop returns while a
// tools/call is still running in its goroutine, so a host that closes stdin
// straight after a call can lose the response (openv-mcp's main returns and
// the process exits). Changing that is a behavior change, not a refactor.
func TestServeStdioReturnsAtEOFWithoutWaitingForInFlightCalls(t *testing.T) {
	t.Setenv(EnvToolAllowlist, "block")
	started, release := make(chan struct{}), make(chan struct{})
	tools := []Tool{{
		Name:        "block",
		Description: "blocks until the test releases it",
		InputSchema: schema(nil, map[string]interface{}{}),
		Handler: func(*Client, map[string]interface{}) (string, error) {
			close(started)
			<-release
			return "late", nil
		},
	}}
	proc := startStdioProcess(t, nil, tools)

	proc.write(`{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"block"}}` + "\n")
	select {
	case <-started:
	case <-time.After(10 * time.Second):
		t.Fatal("the tool never started")
	}
	if err := proc.stop(); err != nil {
		t.Fatalf("ServeStdio at EOF with a call in flight = %v, want it to return nil without waiting", err)
	}
	close(release)
	if line := proc.readLine(); !strings.Contains(line, `"text":"late"`) {
		t.Fatalf("late response = %q, want the released call's result written after ServeStdio returned", line)
	}
}
