package contract

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
	"testing"
)

// jsonBytes is testdata/contract.json: two-space indent, no HTML escaping,
// a trailing newline, as contracts/vocab.json is written.
func (c contract) jsonBytes(t *testing.T) []byte {
	t.Helper()
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(c); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

const tsHeader = `// Code generated by go test ./internal/contract (refactor plan X4a). DO NOT EDIT.
//
// The Go vocabularies the frontend reads, each written from its Go catalogue,
// with the same values as internal/contract/testdata/contract.json. A stale
// copy fails ` + "`go test ./internal/contract/...`" + `; after a deliberate change to a
// vocabulary in Go, regenerate both files with:
//
//   ` + regenerate + `
//
// Each union type is derived from the constant above it, so it names exactly
// the values Go has.
`

// tsField is one property of an object contract.ts writes: a string, or a
// list of strings written on one line.
type tsField struct {
	name  string
	value any
}

type tsObject []tsField

// tsConst is one exported constant of contract.ts, a list of strings or of
// objects, and the union type derived from it: from the list itself, or
// from the objects' field index.
type tsConst struct {
	doc      string
	name     string
	typeName string
	index    string
	strings  []string
	objects  []tsObject
}

// typescript is frontend/src/generated/contract.ts. Its names avoid every
// declaration name S13's vitest (frontend/src/arch/vocabParity.test.ts)
// locates a hand-written copy by, since a second declaration of one would
// leave that reader unable to tell which is the copy.
func (c contract) typescript() []byte {
	consts := []tsConst{
		{doc: "The feature keys of release.Registry, in registry order (internal/domain/release).",
			name: "FEATURE_KEYS", typeName: "FeatureKey", strings: c.FeatureKeys},
		{doc: "The domain event types: the constant block of events.ArtifactCreated (internal/domain/events), in " +
			"declaration order.",
			name: "DOMAIN_EVENT_TYPES", typeName: "DomainEventType", strings: c.EventTypes},
		{doc: "The event names the server sends on an SSE stream, sorted: S6's contracts/sse-events.json, which " +
			"internal/api's TestSSEContract writes from the Go sources.",
			name: "SSE_EVENT_NAMES", typeName: "SseEventName", strings: c.SSEEvents},
		{doc: "The API's machine-readable error codes: the constant block of api.ErrCodeEmailUnverified " +
			"(internal/api), in declaration order.",
			name: "API_ERROR_CODES", typeName: "ApiErrorCode", strings: c.ErrorCodes},
		{doc: "The link type rules of links.GetLinkTypeRules, with their Go text (internal/domain/links).",
			name: "LINK_TYPE_RULES", typeName: "LinkType", index: "type", objects: mapObjects(c.LinkRules,
				func(r linkRule) tsObject {
					return tsObject{{"type", r.Type}, {"label", r.Label}, {"inverseLabel", r.InverseLabel},
						{"allowedFromTypes", r.AllowedFromTypes}, {"allowedToTypes", r.AllowedToTypes},
						{"description", r.Description}}
				})},
		{doc: "The artifact types of artifacts.TypeCatalog, with their labels (internal/domain/artifacts).",
			name: "ARTIFACT_TYPE_CATALOG", typeName: "ArtifactTypeValue", index: "value", objects: mapObjects(
				c.ArtifactTypes, func(a artifactType) tsObject { return tsObject{{"value", a.Value}, {"label", a.Label}} })},
		{doc: "The artifact statuses, the constant block of artifacts.StatusDraft in declaration order, each with " +
			"the statuses artifacts.CanTransition allows next (internal/domain/artifacts).",
			name: "ARTIFACT_STATUSES", typeName: "ArtifactStatusValue", index: "value", objects: mapObjects(
				c.ArtifactStatuses, func(s artifactStatus) tsObject { return tsObject{{"value", s.Value}, {"next", s.Next}} })},
		{doc: "The workspace plans: the constant block of orgs.PlanSingle in declaration order, the legacy " +
			"aliases included (internal/domain/orgs).",
			name: "WORKSPACE_PLANS", typeName: "WorkspacePlan", strings: c.Plans},
		{doc: "The V&V gap lists, by the JSON key GET /api/v1/projects/{id}/vv/gaps sends them under, with the " +
			"title the reports print, in report order (internal/domain/reports).",
			name: "VV_GAP_LABELS", typeName: "VvGapKey", index: "key", objects: mapObjects(c.GapLabels,
				func(g gapLabel) tsObject { return tsObject{{"key", g.Key}, {"label", g.Label}} })},
		{doc: "The agent providers of providers.KnownProviders, in display order (internal/domain/providers).",
			name: "AGENT_PROVIDERS", typeName: "AgentProvider", strings: c.Providers},
	}
	var b strings.Builder
	b.WriteString(tsHeader)
	for _, k := range consts {
		b.WriteString("\n")
		k.write(&b)
	}
	return []byte(b.String())
}

func mapObjects[T any](items []T, object func(T) tsObject) []tsObject {
	out := make([]tsObject, 0, len(items))
	for _, it := range items {
		out = append(out, object(it))
	}
	return out
}

func (k tsConst) write(b *strings.Builder) {
	lines := wrap(k.doc, 76)
	if len(lines) == 1 {
		fmt.Fprintf(b, "/** %s */\n", lines[0])
	} else {
		b.WriteString("/**\n")
		for _, l := range lines {
			fmt.Fprintf(b, " * %s\n", l)
		}
		b.WriteString(" */\n")
	}
	fmt.Fprintf(b, "export const %s = [\n", k.name)
	for _, s := range k.strings {
		fmt.Fprintf(b, "  %s,\n", tsString(s))
	}
	for _, o := range k.objects {
		b.WriteString("  {\n")
		for _, f := range o {
			fmt.Fprintf(b, "    %s: %s,\n", f.name, tsValue(f.value))
		}
		b.WriteString("  },\n")
	}
	b.WriteString("] as const;\n")
	index := "[number]"
	if k.index != "" {
		index += "[" + tsString(k.index) + "]"
	}
	fmt.Fprintf(b, "export type %s = (typeof %s)%s;\n", k.typeName, k.name, index)
}

// tsValue writes a field's value: a string, or a list of strings on one
// line.
func tsValue(v any) string {
	switch v := v.(type) {
	case string:
		return tsString(v)
	case []string:
		quoted := make([]string, len(v))
		for i, s := range v {
			quoted[i] = tsString(s)
		}
		return "[" + strings.Join(quoted, ", ") + "]"
	}
	panic(fmt.Sprintf("contract.ts cannot write a %T", v))
}

// tsString is s as a single-quoted TypeScript string literal, the frontend's
// quote style. Backslash, the quote, line terminators and other control
// characters are escaped; everything else is written as itself.
func tsString(s string) string {
	var b strings.Builder
	b.WriteByte('\'')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '\'':
			b.WriteString(`\'`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		case ' ', ' ':
			fmt.Fprintf(&b, `\u%04x`, r)
		default:
			if r < 0x20 || r == 0x7f {
				fmt.Fprintf(&b, `\x%02x`, r)
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('\'')
	return b.String()
}

// wrap splits text into lines of at most width bytes at spaces (a longer
// word gets a line of its own).
func wrap(text string, width int) []string {
	var lines []string
	line := ""
	for _, w := range strings.Fields(text) {
		switch {
		case line == "":
			line = w
		case len(line)+1+len(w) <= width:
			line += " " + w
		default:
			lines = append(lines, line)
			line = w
		}
	}
	return append(lines, line)
}

func TestTSString(t *testing.T) {
	for in, want := range map[string]string{
		"verified by":                      `'verified by'`,
		"the parent's verification":        `'the parent\'s verification'`,
		`a\b`:                              `'a\\b'`,
		"two\nlines\r\tand a tab":          `'two\nlines\r\tand a tab'`,
		"NFRs & <constraints>":             `'NFRs & <constraints>'`,
		"caf\u00e9 \u2014 \u2028 \u2029":   "'caf\u00e9 \u2014 \\u2028 \\u2029'",
		"bell\x07 del\x7f":                 `'bell\x07 del\x7f'`,
		"":                                 `''`,
		"\"double\" quotes stay as they":   `'"double" quotes stay as they'`,
		"${not} a `template` literal here": "'${not} a `template` literal here'",
	} {
		if got := tsString(in); got != want {
			t.Errorf("tsString(%q) = %s, want %s", in, got, want)
		}
	}
}

func TestWrap(t *testing.T) {
	got := wrap("one two three four", 9)
	want := []string{"one two", "three", "four"}
	if strings.Join(got, "|") != strings.Join(want, "|") {
		t.Errorf("wrap = %q, want %q", got, want)
	}
	if got := wrap("short", 76); len(got) != 1 || got[0] != "short" {
		t.Errorf("wrap(short) = %q", got)
	}
}
