// Command envdoc writes the tables of docs/env-vars.md (refactor plan step
// D1) from the environment variable inventory of step S8.
//
//	go run ./internal/tools/envdoc
//
// The names, and where the code passes a constant, the defaults come from
// internal/archtest/testdata/env_vars.txt, which TestEnvInventory keeps equal
// to what the code reads. What each variable does, its area (an area of
// docs/areas.json), the program that reads it and any default the inventory
// cannot see come from vars.json beside this file. envdoc replaces the part of
// docs/env-vars.md between its two marker lines and leaves the rest, the
// hand-written prose, as it is. It refuses to write when a name the
// inventory lists has no entry in vars.json, when vars.json describes a name
// the inventory does not list, or when an entry's default contradicts the
// inventory's. envdoc_test.go fails when the file is not what envdoc writes.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const (
	inventoryFile = "internal/archtest/testdata/env_vars.txt"
	varsFile      = "internal/tools/envdoc/vars.json"
	areasFile     = "docs/areas.json"
	docFile       = "docs/env-vars.md"

	beginMarker = "<!-- BEGIN GENERATED by go run ./internal/tools/envdoc: edit internal/tools/envdoc/vars.json, not this table -->"
	endMarker   = "<!-- END GENERATED -->"
)

func main() {
	cwd, err := os.Getwd()
	if err == nil {
		var root string
		if root, err = findRoot(cwd); err == nil {
			err = write(root)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "envdoc:", err)
		os.Exit(1)
	}
}

// findRoot walks up from dir to the directory holding go.mod.
func findRoot(dir string) (string, error) {
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("no go.mod above the working directory")
		}
		dir = parent
	}
}

// write rewrites the generated part of docs/env-vars.md.
func write(root string) error {
	path := filepath.Join(root, filepath.FromSlash(docFile))
	old, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	doc, err := Generate(root, string(old))
	if err != nil {
		return err
	}
	if doc == string(old) {
		return nil
	}
	return os.WriteFile(path, []byte(doc), 0o644)
}

// Generate returns doc with the part between its markers replaced by the
// tables the inventory and vars.json give.
func Generate(root, doc string) (string, error) {
	begin := strings.Index(doc, beginMarker+"\n")
	end := strings.Index(doc, endMarker)
	if begin < 0 || end < begin {
		return "", fmt.Errorf("%s needs the line %q and, below it, the line %q", docFile, beginMarker, endMarker)
	}
	tables, err := Tables(root)
	if err != nil {
		return "", err
	}
	start := begin + len(beginMarker) + 1
	return doc[:start] + tables + doc[end:], nil
}

// Row is one row of the inventory: a variable, how it is read, its default.
type Row struct {
	Name, Read, Default string
}

var nameRe = regexp.MustCompile(`^[A-Z][A-Z0-9_]*$`)

// ReadInventory reads the variable rows of env_vars.txt, leaving out the
// comments and the exemptions after them.
func ReadInventory(root string) ([]Row, error) {
	data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(inventoryFile)))
	if err != nil {
		return nil, err
	}
	var rows []Row
	for _, line := range strings.Split(string(data), "\n") {
		f := strings.Split(line, "\t")
		if len(f) == 3 && nameRe.MatchString(f[0]) {
			rows = append(rows, Row{f[0], f[1], f[2]})
		}
	}
	if len(rows) == 0 {
		return nil, fmt.Errorf("%s lists no variable", inventoryFile)
	}
	return rows, nil
}

// Var is what vars.json says of one variable.
type Var struct {
	Area    string `json:"area"`
	ReadBy  string `json:"read_by"`
	Default string `json:"default,omitempty"`
	Text    string `json:"text"`
}

type varsDoc struct {
	About string         `json:"about"`
	Vars  map[string]Var `json:"vars"`
}

func readVars(root string) (map[string]Var, error) {
	data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(varsFile)))
	if err != nil {
		return nil, err
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	var v varsDoc
	if err := dec.Decode(&v); err != nil {
		return nil, fmt.Errorf("%s: %w", varsFile, err)
	}
	return v.Vars, nil
}

type area struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func readAreas(root string) ([]area, error) {
	data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(areasFile)))
	if err != nil {
		return nil, err
	}
	var idx struct {
		Areas []area `json:"areas"`
	}
	if err := json.Unmarshal(data, &idx); err != nil {
		return nil, fmt.Errorf("%s: %w", areasFile, err)
	}
	return idx.Areas, nil
}

// Tables renders one table per area, in the order of docs/areas.json.
func Tables(root string) (string, error) {
	rows, err := ReadInventory(root)
	if err != nil {
		return "", err
	}
	vars, err := readVars(root)
	if err != nil {
		return "", err
	}
	areas, err := readAreas(root)
	if err != nil {
		return "", err
	}
	known := map[string]bool{}
	for _, a := range areas {
		known[a.Name] = true
	}
	defaults := map[string][]string{}
	var names []string
	for _, r := range rows {
		if _, seen := defaults[r.Name]; !seen {
			names = append(names, r.Name)
		}
		defaults[r.Name] = appendUnique(defaults[r.Name], r.Default)
	}
	var problems []string
	byArea := map[string][]string{}
	for _, name := range names {
		v, ok := vars[name]
		switch {
		case !ok:
			problems = append(problems, fmt.Sprintf("%s is read by the code (%s) but has no entry in %s", name, inventoryFile, varsFile))
			continue
		case !known[v.Area]:
			problems = append(problems, fmt.Sprintf("%s: area %q is not an area of %s", name, v.Area, areasFile))
		case strings.TrimSpace(v.Text) == "" || strings.TrimSpace(v.ReadBy) == "":
			problems = append(problems, fmt.Sprintf("%s: an entry needs read_by and text", name))
		}
		if _, err := defaultCell(defaults[name], v.Default); err != nil {
			problems = append(problems, fmt.Sprintf("%s: %v", name, err))
		}
		byArea[v.Area] = append(byArea[v.Area], name)
	}
	for _, name := range sortedKeys(vars) {
		if _, ok := defaults[name]; !ok {
			problems = append(problems, fmt.Sprintf("%s has an entry in %s but the code no longer reads it (%s): remove the entry", name, varsFile, inventoryFile))
		}
	}
	if len(problems) > 0 {
		return "", errors.New(strings.Join(problems, "\n"))
	}
	var b strings.Builder
	fmt.Fprintf(&b, "\n%d variables, in %d inventory rows (a variable read in more than one place has a row per read).\n", len(names), len(rows))
	for _, a := range areas {
		list := byArea[a.Name]
		if len(list) == 0 {
			continue
		}
		sort.Strings(list)
		fmt.Fprintf(&b, "\n### %s\n\n| Variable | Read by | Default | What it does |\n|---|---|---|---|\n", a.Name)
		for _, name := range list {
			v := vars[name]
			def, _ := defaultCell(defaults[name], v.Default)
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", name, cell(v.ReadBy), cell(def), cell(v.Text))
		}
	}
	b.WriteString("\n")
	return b.String(), nil
}

// defaultCell is the Default column: the inventory's constant when every read
// of the variable passes the same one, otherwise the entry's own default,
// which the inventory cannot see (a computed fallback, a direct read's inline
// default). An entry may not restate or contradict a constant the inventory
// already holds, except the empty string, which a getter often passes to
// mean "decided later" (RUNNER_POOL's empty value is the pool "default").
func defaultCell(inventory []string, own string) (string, error) {
	constant := len(inventory) == 1 && inventory[0] != "(computed)" && inventory[0] != "-"
	switch {
	case constant && own != "" && inventory[0] == `""`:
		return own, nil
	case constant && own != "":
		return "", fmt.Errorf("the inventory gives the default %s; drop the entry's default", inventory[0])
	case constant:
		return formatConstant(inventory[0]), nil
	case own == "":
		return "", fmt.Errorf("the inventory has no single constant default (%s): give the entry a default", strings.Join(inventory, ", "))
	}
	return own, nil
}

// formatConstant renders an inventory default: a quoted string unquoted in a
// code span, the empty string as none.
func formatConstant(d string) string {
	if d == `""` {
		return "none"
	}
	return "`" + strings.Trim(d, `"`) + "`"
}

// cell escapes the pipes a table cell may not hold bare.
func cell(s string) string {
	return strings.ReplaceAll(strings.TrimSpace(s), "|", `\|`)
}

func appendUnique(list []string, s string) []string {
	for _, x := range list {
		if x == s {
			return list
		}
	}
	return append(list, s)
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
